- name: App Collection f5_bigip
  hosts: lb
  connection: httpapi
  gather_facts: false

  collections:
    - f5networks.f5_bigip

  vars_files:
  - ../../creds/autows_bigip_creds.yaml  
  
  vars:
    ansible_host: "{{ bigip_host }}"
    ansible_user: "{{ bigip_user }}"
    ansible_httpapi_password: "{{ bigip_pass }}"
    ansible_httpapi_port: 443
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: false
    partition: ansible_declarative_example
    state: present
    apps:
      - name: web
        vsip: 10.39.2.1
        vsport: 80
        memberport: 8080
        poolname: web_pool
        members:
          - 10.39.2.2
          - 10.39.2.3
          - 10.39.2.4
      - name: api
        vsip: 10.39.3.1
        vsport: 3000
        memberport: 3000
        poolname: api_pool
        members:
          - 10.39.3.2
          - 10.39.3.3
          - 10.39.3.4
      - name: web2
        vsip: 10.39.4.1
        vsport: 80
        memberport: 8080
        poolname: web2_pool
        members:
          - 10.39.4.2
          - 10.39.4.3
          - 10.39.4.4

  tasks:   

    - name: Create AS3
      f5networks.f5_bigip.bigip_as3_deploy:
        content: "{{ lookup('template', 'declarations/as3_templ.json') }}"
      tags: [ deploy ]
      when: state == "present"

    - name: Delete AS3
      f5networks.f5_bigip.bigip_as3_deploy:
        state: "{{ state }}"
        tenant: "{{ partition }}"
      when: state == "absent"

